### ISSUE TITLE
Nexus Staging support

### ISSUE THREAD

**Issue by shillner** [shillner/unleash-maven-plugin#39]
As discussed in #37 Nexus staging support could be part of the plugin or an external hook.

**Comment by kasunbg** [comment]
Subscribed for notifications to see future updates. :-)

**Comment by jgangemi** [comment]
strangely enough, i am now interested in seeing this type of support and would like to weigh in...

is there a specific reason you aren't integrating with the `maven-install-plugin` and `maven-deploy-plugin` directly? doing this would allow you to leverage all the features they already implement, such as being able to push all artifacts from a reactor build at the end instead of one by one (which i always found stupid anyway b/c you end up in a weird state w/ snapshots, but i digress).

if you did integrate w/ those plugins, i believe (from what i've read) that the nexus plugin would work seamlessly w/ it b/c it would disable the `deploy` plugin and do it's own thing.

@kasunbg: i think you can still use the staging plugin and unleash at the same time to close a repository but i need to investigate that a little more.

**Comment by kasunbg** [comment]
@jgangemi sorry for the late response. Nexus staging plugin is not open-source. So, we can't use it, unfortunately. The Jenkins M2 Release Plugin has this support. I did a few improvements to do the Staging repo release in addition to repo close in there as well. 

So, M2 release plugin does the job, at least barely. We need proper recovery and rollback mechanisms in case of failure. I guess that's where the advantage of unleash plugin comes in. (it's an unusual name btw ;) )

**Comment by jgangemi** [comment]
@kasunbg what do you mean it's not open source?

https://github.com/sonatype/nexus-maven-plugins/tree/master/staging/maven-plugin

**Comment by kasunbg** [comment]
Well, true. The plugin is released under EPL. But, I find the licensing terms a bit confusing. See the 'Notes' section in the link you sent. So, not sure how to place this in my org that has strong principles on open-source culture. Anyway, that's a separate discussion!

> Notes:
> 
> to build this plugin from sources you need access to Sonatype commercial components!
> to use this plugin in your build, access to Central only is enough!

**Comment by shillner** [comment]
Hi, the reason for me to not install and deploy at the end of the release build was that the installation and deployment of the artifacts should be done at the very last steps of the release since the deployment cannot be undone automatically. If it would be performed during the build process any errors during tagging, ... would make it impossible to fully roll back all actions done so far. This is the reason why the build performs a verify only and installation and deployment are postponed until everything else is done.

**Comment by jgangemi** [comment]
i do agree that it's dumb those plugins install jars for each module in a reactor project but there is now an option that will force them to install at the end (it has been working rather well for me).

i'm curious to know how this will all play into site generation as part of the release - i guess time will tell...

**Comment by shillner** [comment]
I know this option and am also using it in some setups but installing at the end of the build ist still too early in the whole release process since we need to adapt the poms and set the next development version... If something goes wrong there there is no chance to rollback the deployment.  Dienstag, 20 September 2016, 09:38nachm. +02:00 von Jae Gangemi  notifications@github.com :

**Comment by jgangemi** [comment]
but aren't there two stages to that? pushing the released artifacts and then transforming the poms to the next development version? 

i'm not arguing for one or the other, just trying to better understand.

**Comment by kasunbg** [comment]
@shillner yes, a deployment cannot be undone automatically. But, that's why Nexus has provided the staging repositories. That means the artifacts don't go into the releases repo directly, but goes through a staging repo which can contain a set of ruleset that does validation on your artifacts.

With the Nexus staging repositories, you have two stages to promote the artifacts into a releases repository. First, you need to 'close' the staging repo. (that's when the validation ruleset is run.) Then, you need to 'release' the repo. 

Some people will be fine with automating only the closing of staging repo which will validate their release. I'm interested in releasing the repos as well since we have hundreds of repos, and getting them out as soon as possible is more attractive.

**Comment by shillner** [comment]
Good point but keep in mind that not everybody uses Nexus as their artifact repository. And since this functionality shall be generic we cannot rely on those proprietary features. The aether, which is my reference for accessing the artifact repositories, does not provide methods for the deletion of artifacts.

Just for clarification, @jgangemi asked for a better explanation of the current process:

Since we were often facing massive problems with the release plugin leaving us in unpredictable states where we had to check all involved systems (SCM, Nexus, file shares, ...) over and over, we decided to see the whole process as kind of an atomic step. Our (we at the project where we kicked-off the development of the plugin) opinion is that if one step of the whole process fails everything should be rolled back to its initial state. This also involves the preparation for the next development cycle. Sure this can be seen as an extra step that is not so important but it was annoying to check the real state at which the release plugin left us again and again. So this was one of the main constraints and this is why the installation and deployment run as the very last steps, away from the "normal" build.

Hope this helps to understand my motivation ;)

Nevertheless the staging support is still in the queue but I would also appreciate if anyone sends me a PR, maybe as an extra step integrated in the plugin or totally separated from the plugin as a processing hook.
