### ISSUE TITLE
Customized deployment - maven-deploy-plugin

### ISSUE THREAD

**Issue by coschneider** [shillner/unleash-maven-plugin#56]
Is it possible to use the maven-deploy-plugin within an unleash perform-tycho run to handle artifact deployment via skip true/false configuration?

**Comment by shillner** [comment]
Out of the box, no. You could override the workflow and call the deploy plugin but then it would not be aware of the artifacts produced during the build. The actual build of the release artifacts is done by performin a clean verify. Deployment is postponed until the end of the process, by design!

What exactly are you trying to achieve? You could also skip the deployment by overriding the default workflow with a custom one that omits the deployment step.
