### ISSUE TITLE
Unclear on usage of releaseArgs

### ISSUE THREAD

**Issue by alevinetx** [shillner/unleash-maven-plugin#73]
The documentation for releaseArgs says:
```
Specify additional arguments for the release build here. Arguments can be system properties (-D...), batch mode (-B), debug mode (-X) or anything else you can pass to the build.
```
But, another ticket states that it's not possible to pass values to the build, but just to the jdk itself.  

Regardless, my first hurdle is properly formatting the parameter value.   Specifically, I'm trying to set "altDeploymentRepository"

Source: http://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#altDeploymentRepository
```
mvn  -Dunleash.releaseArgs=-DaltDeploymentRepository=serverid::default::http://myrepo.com
```
In this format, the build errors out with:

```
[INFO] 10:14:21,241  Starting release build.
[DEBUG] 10:14:21,254  	Using maven home: C:\dev\maven\apache-maven-3.3.9\bin\..
Unable to parse command line options: Missing argument for option: D
usage: mvn [options] [<goal(s)>] [<phase(s)>]
```
I tried removing the -D so it was just a single key=value.

I also tried (from: http://stackoverflow.com/questions/13163890/override-maven-release-repository-durning-deploy)
```
... -Darguments=-DaltDeploymentRepository=...
```
Neither of those error out, but the value doesn't seem to be passed wherever it needs to end up.  I'm spinning in circles trying to discover where I need to pass values, and the format.  When I passed in "-X" as the value for releaseArgs, it doesn't error out, but it also doesn't provide the debug output.

Can you provide any insight/assistance?  

Thank you !

**Comment by shillner** [comment]
Hi, I know there is some need for more doumentation of the plugin but time is rare these days, unfortunately.

What you are trying cannot work since the deployment of the artifacts is not performed using the maven-deploy-plugin but through the aether API.
It would be necessary to provide a further parameter for an alternative deployment repository. On the other hand there is another issue for the execution of plugins bound to the install and deploy phases since these phases are never executed. I'm not quite sure if this is possible at all.

**Comment by alevinetx** [comment]
Okay, that makes sense. I can change my strategy without a problem.   

Can you provide some examples/use cases of when we'd want to use that parameter setting, and the format of the key/value pairs?  The documentation says we can use -X, but that seemingly doesn't impact the aether API, assuming I set the format correctly.

Thanks again !

**Comment by shillner** [comment]
Hi, ok setting an alternative deployment repository from outside is not possible at the moment since the aether API calls used to deploy the artifacts simply takes the distribution management artifact repository of the project configuration. I'm not sure whether it is possible to specifiy the repository URI as a property reference but this way you could override this URI from outside using a system property (@alevinetx could you try this?)

System properties can be passed to the relase build using the releaseArgs parameter. Simply do the following:
`-Dunleash.releaseArgs="-Dproperty1Key=property1Value -Dproperty2Key=property2Value"`

**Comment by alevinetx** [comment]
I did try setting it as recommended, but that format fails (see my original post), so that's not working, yet.  I have a working work around, so this is a minor issue for me.   I would suggest that there is a bug in passing -D to releaseArgs, unless that format just isn't correct

**Comment by shillner** [comment]
Hi, sorry for the confusion but my time was a bit short and I digged out a wrong format. This should do it:
`-Dunleash.releaseArgs="detail=true,skipTests=true"`

**Comment by shillner** [comment]
Going to close this issue. I created an issue for update of the docs: #74
