### ISSUE TITLE
Tag creation differs from maven release plugin

### ISSUE THREAD

**Issue by DG1001** [shillner/unleash-maven-plugin#79]
Releasing works really well, although I'm having a problem with the way the tag is created.

Structure of 'projectx' (artifactId = projectx) in scm:

/trunk/projectx
/branches
/tags
  
In order to comply to maven release plugin I use '@{project.artifactId}-@{project.version}' as 'SCM Tag Name Pattern'

After releasing version '1.0.0' I get:
/tags/projectx-1.0.0/projectx/

The maven release plugin would create:
/tags/projectx-1.0.0
without the additional sub directory.

Is there a way to avoid the additional folder directly after the tag name?

**Comment by shillner** [comment]
Hi, the tag URL calculation depends on the connection URL from which your local working copy was checked out. The tag URL is calculated as the name of the tags folder + the tag name + any subfolders of the original checkout location. The latter leads to the path you've posted here. See here for more details: [ScmProviderSVN#calculateTagConnectionString](https://github.com/shillner/unleash-scm-provider-svn/blob/ba6db6d416ce280cc0afca8360789b17fae14610/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/ScmProviderSVN.java#L585) and [SVNUrlUtils#getUrlSubPath](https://github.com/shillner/unleash-scm-provider-svn/blob/ba6db6d416ce280cc0afca8360789b17fae14610/src/main/java/com/itemis/maven/plugins/unleash/scm/providers/util/SVNUrlUtils.java#L53)

I wouldn't change this because there was a requirement for this behavior but feel free to investigate additional behavior and maybe provide a PR with an extension.

**Comment by Weltraumschaf** [comment]
This is not the standard behavior like in Maven release plugin (http://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html#tagNameFormat). In SVN it is possible to "define a project" as a subdirecotry in the standard layout. The standard behavior of Maven is to tag into "'@{project.artifactId}-@{project.version}". So by default this plugin should behave the same like the Maven release plugin to not break tool chains. Your requirement should be a configurable option like "tagNameFormat" in Maven release plugin. Would that bean option for you?

**Comment by shillner** [comment]
First of all nobody says that new plugins have to stick to the behavior of older ones! The current behavior is absolutely wanted and it is not necessary to imitate each and every single option and its defaults of the release plugin. So the tag name pattern's default won't change since this plugin was mainly implemented for a client of mine based on concrete requirements.

As I told, implementing an extension that makes the URL subpath generation configurable is an option and I'm waiting for a proposal or a PR. We think that it is necessary to keep the subpaths since you are not checking out from trunk but a subfolder of trunk. There may be many projects besides the one you've checked out and creating a tag without the subpath wouldn't match the trunks structure and you wouldn't be able to create f.i. tag 1.1.0 for all of the projects lying under trunk. I took a note of your requirement and asked you to please provide a PR for it but simply telling me that the current implementation is wrong because it doesn't behave like the release-plugin isn't the way things should work here! So implementing our specific requirements as configurable options is no option because the plugin development is driven by these requirements!

Please feel free to contribute to the plugin, I appreciate it!

**Comment by DG1001** [comment]
Due to our tight schedule we decided to postpone the PR and use a custom workflow definition with an exec call to svn for the few projects we still haven't moved to git.
I hope we will be able to provide the PR at a later point in time. 

Thanks for your support and for creating the plugin!
