### ISSUE TITLE
`META-INF/maven/<Group Id>/<Artifact Id>/pom.xml` in release jars containing injected `artifact-spy-plugin`

### ISSUE THREAD

**Issue by tan9** [shillner/unleash-maven-plugin#86]
Seems it is an unavoidable *feature* in current `perform` workflow:

```
addSpyPlugin
buildReleaseArtifacts
removeSpyPlugin
```

I don't know what library will use those POMs inside artifact jar. This issue is created for reference.

![image](https://user-images.githubusercontent.com/638068/29021501-510cccec-7b98-11e7-991b-55e11019550a.png)

**Comment by shillner** [comment]
Yes, it is not avoidable since we're not able to determine all the artifacts that are built during the actual release build from "outside". This means that we "unfortunately" have to hook into the verify phase of the release build to determine the artifacts for later installation and deployment. Maybe there is another optiona available anywhere when calling the maven build (listeners, ...) but I didn't find one yet.

**Comment by shillner** [comment]
I flagged it as an enhancement in order to keep it for later ;)
