### ISSUE TITLE
Why extra files for workflow configuration?

### ISSUE THREAD

**Issue by pfink** [shillner/unleash-maven-plugin#87]
Hi @shillner,
is there a specific reason why you choosed to make the workflow configurable via seperated files? I think it has some disadvantages, e.g. you cannot integrate your workflows into a global super POM / corporate POM and reuse them in every project. Instead, you have to copy the workflow files into every single project again. Wouldn't it be better if workflow could be defined directly within the POM and then be reused by child projects?

Idea / Example:

```
                [..]
                <plugin>
                  <groupId>com.itemis.maven.plugins</groupId>
                  <artifactId>unleash-maven-plugin</artifactId>
                  <version>2.6.0</version>
                  <dependencies>
                    <dependency>
                      <groupId>com.itemis.maven.plugins</groupId>
                      <artifactId>unleash-scm-provider-git</artifactId>
                      <version>2.1.0</version>
                    </dependency>
                  </dependencies>
                  <configuration>
                    <workflows>
                      <workflow>
                        <name>my-first-workflow</name>
                        <steps>
                          <tryfinally>
                            <try>
                              <step>firstStep</step>
                              <step>secondStep</step>
                            </try>
                            <finally>
                              <parallel>
                                <step>thirdStep</step>
                                <step>fourthStep</step>
                              </parallel>
                              <step>lastStep</step>
                            </finally>                            
                          </tryfinally>                        
                        </steps>
                      </workflow>
                      <workflow>
                        <name>my-second-workflow</name>
                        [..]
                      </workflow>
                    </workflows>          
                  </configuration>                  
                </plugin>
                [..]
```

**Comment by shillner** [comment]
Hi, there was no special reason for that but I also don't like the POM file format which makes it hard to express more complex configurations. We typically use this workflow mechanism by putting a shared workflow onto a shared drive the Jenkins CI server has access to and use it from there. We don't share it through the SCM since it is not a real part of the sources...
But if you're interested in trying things out please feel free to implement such a mechanism. PRs are very welcome ;)

Btw. the implementation of the workflow stuff is part of the CDI-base of this plugin: [maven-cdi-plugin-utils](https://github.com/shillner/maven-cdi-plugin-utils)

**Comment by pfink** [comment]
Thanks for your input! I'm not sure whether I'll come up with a PR for this, but I opened an issue just to document the feature request: shillner/maven-cdi-plugin-utils#22
