### ISSUE TITLE
automatically add relevant scm implementations

### ISSUE THREAD

**Issue by jorgheymans** [shillner/unleash-maven-plugin#93]
Hi,

It would be a nice enhancement if the jenkins plugin would automatically detect the type of scm being used, if possible, and enhance the POM internal model with the correct plugin dependency. That way below changes would not be required in the project pom and everything would work out of the box :-)

```
  <build>
    <plugins>
      <plugin>
        <groupId>com.itemis.maven.plugins</groupId>
        <artifactId>unleash-maven-plugin</artifactId>
        <version>2.7.2</version>
        <dependencies>
          <dependency>
            <groupId>com.itemis.maven.plugins</groupId>
            <artifactId>unleash-scm-provider-git</artifactId>
            <version>2.1.0</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
```

**Comment by shillner** [comment]
Hi,

sorry but this is not easily possible. It would require the Jenkins plugin to do some complex logic and POM adaptions. From my point of view there are several arguments against it:

- Currently the Jenkins plugin is just a wrapper around the Jenkins Maven plugin (Maven job) without implicit logic. It simply collects all necessary information to trigger the unleash plugin and does so. I think this is the correct approach since everything else is performed by the actual unleash maven plugin.
- The approach would introduce some more magic to the process which I see critical since it is not that easy to find a provider implementation (which one and which version).
- This approach would also result in additional POM changes in the SCM.

But please feel free to implement a prototype if you really need this feature!

**Comment by jorgheymans** [comment]
ok understood thanks for the reply.
